### ISSUE TITLE
Create a PersonGroupValidator class

### ISSUE THREAD

**Issue by sohlae** [josh-monreal/face-api#59]
## TASKS
- [x] Remove unnecessary `using` statements
- [x] Create a `PersonGroupDto` object
- [x] Inherit from the `AbstractValidator<PersonGroupDto>`
- [x] Ensure that the input matches the regular expression `^[a-z0-9_-]{1,64}$`
- [x] Modify the IPersonGroupLogic's and PersonGroupLogic's `Create` methods to accept a `PersonGroupDto` as a parameter
- [x] Modify the Initializer's `ExecutePersonGroupCreation()` method to provide a `PersonGroupDto` as an argument to the PersonGroupLogic's `Create` method
- [x] Update the unit tests of the PersonGroupLogic's `Create` method to make it pass
