### ISSUE TITLE
Create a PersonValidator class

### ISSUE THREAD

**Issue by sohlae** [josh-monreal/face-api#61]
## TASKS
- [x] Remove unnecessary `using` statements
- [x] Create a `PersonDto` object
- [x] Inherit from the `AbstractValidator<PersonDto>`
- [x] Ensure that the input matches the regular expression `.{1,128}` for the `Name` property
- [x] Modify the IPersonLogic's and PersonLogic's `Create` methods to accept a `PersonDto` as a parameter
- [x] Modify the Initializer's `ExecutePersonCreation()` method to provide a `PersonDto` as an argument to the PersonLogic's `Create` method
- [x] Update the unit tests of the PersonLogic's `Create` method to make it pass
